* [2019-12-10 Tue] from 諸橋..品質管理
品質管理で学んだことに、文字をいれてみました。
こんな感じでいかがでしょうか。

* [2019-12-10 Tue] from 石澤..点検
点検：点検計画に基づき各業務の点検をおこなっている。作業の品質を保証するために、業務実施状況を確認している。範囲・頻度は手順書に基づき、点検実施計画書に定めている。
自己点検：資材の記録、保存、作業記録等の定期点検をおこなっている。
点検については、鈴木さんのお話などで品質管理チームの作業イメージが強いのですが、自己点検についてはマッピングチームの手順書しか把握してなかったので、ぼやかしました。
帰任してから内部説明のために、点検と自己点検の違いを頑張って覚えたつもりでしたがもう忘れました(笑)

文章の作成ありがとうございます。
私、点検チームに所属していましたが、”点検”の記載内容は正しいと思います。
こちらに関しては、違うチームの自己点検実施状況のみならず、実際のログを確認す
るなど、正しく自己点検されているかも確認していました。

自己点検については、他のチームの状況が分からなく、判断がつかないのです。
品管チームに関しては、石澤さんが書いてくださった内容に間違いありません！
  
* [2019-12-09 Mon] from all
** about 「概念」
*** asa
 言葉の使い方ですが、「概念」でいいと思います。
 例えば、標準マスタがどのように作られているか、コードと病名は1対1の関係であることが、何かで決められていれば「規定外」という言葉もありかなと思います。

*** itoh
 ご連絡ありがとうございます。
 標準マスタのつくりと、病名管理番号は病名表記と1対1であることは仕様書に明文化されておりました。

 ＞高田さん
 規定外か概念外かそれ以外か、今回にふさわしい言葉をご検討いただければと思います。

*** taka
 ひとまず、このままにしてみます。
 規定外、というと、規定にあっていない、という意味なのですが、
 この場合、Layerが違うというか、病態の捉え方が違うという意味だと思いますので、
 概念外、という表記の方が適切なのかなぁと判断していました。
 確かに、他の言い回しがあればよいのかも、なのですが、思いつかない...

** about 設計、分散管理
*** asa 
 さて、資料ですが、気になる部分が2点あります。
 ①　「３．本事業でのQuality」　2枚目のスライド
 MID-NET側が「適切な設計・計画」に対して、臨中ネットが「各施設でのDB方針」
 MID-NET側の「設計」がDB本体やHIS→DBのデータ連携を含む、システムデザイン、「計画」は、運用計画を指しているのかなと思いました。
 なので、ここにある「DB方針」という言葉がしっくりきませんでした。
 この言葉は、データベースの設計・運用などの全体を含むものという意図で使われていると言う理解でよろしかったでしょうか。

*** taka
 そのつもりなのですが、ここでの対比は、システムだDBだ、
 というところにあるわけではないことも、ご理解いただいているかと思います。
 正確性よりも、わかりやすさをとった表現、ということです。
 まずは、DBの方針が違うということを認識すべきでしょう、ということで。

*** asa
 ②最後から2枚目　（提案のスライドです）
 「分散管理を横断管理する部門会」
 これも、もごもごした感があります。
 ここでは、分散管理していても均一なデータを扱うために必要な部門会の提案かと思いますので、
 「分散管理のデータを均一化するための横断的な部門会」
 「分散管理データの均一化を図る横断的部門会」
 ではいかがでしょうか。 （ちょっと長いですか？）

*** taka
 データって、均一にすべき、なんでしょうか？
 ちょっと違和感があります。
 (もごもご、ってなんだろ？)

** about 検査
*** koku
 PMDAのルールに従って、PMDAがJLAC10コードを提案し、拠点との協議後に採用している
 統一単位の採用？結果値の妥当性は分布図または他の方法？

 ■JLAC10の揺らぎ
 MID-NETでは、PMDAのルールに従ってJLAC10コードを提案→拠点調査で協議・承認
 臨中では、臨中ネットで定めたルールに従って、各医療機関がA表を整備する
 という流れなのかなと思います。

 ■単位
 臨中ネットでもMID-NET同様の統一単位が必要になるように思います。
 これは結果値の妥当性を検証するためにもデータを合わせる必要があるので、統一単位が設定された方がブレずに解析ができます。
 結果値の妥当性の検証はMID-NETでは分布図を用いておりましたが、臨中ネットでは分布図以外の方法も検証することが必要かもしれません。

 ■その他
 定性値は、MID-NETは標準化していなかったので省いていいかと思います。
 臨中では、単位情報が含まれているJLAC11を採用することで効率的に運用できるという感じでよいのかなと思います。

*** taka
 特に異論はありません。
 強いていえば、臨中では、各医療機関が整備したA表を、どう確認(Validate)していくか、
 そこまで言及してもよいかなぁ、といった点くらいでしょうか。

** about 点検
*** moro
 作ってくださったスライドみてみました！そして、ちょっと気になることが。
 前に記載したことと重複するかもしれないのですが、”点検”関係のところ。
 自己点検については、作業者自身が自己点検してる場合もあった気がします。
 田中さんや渡辺さんは自分がやった作業を、記載していたんじゃないのかな？
 なんかそんな感じだった気がするのです。
 だから、”同一チームにいる別の作業者が～”って、言いきってよいか心配になりました。

 あと、細かいのですが、”点検・自己点検”より、”自己点検・点検”のほうが、順番どおりでモヤっとしない（笑）

 度々すみません…。
 今更なのですが、組織図（案）や手順書（案）に”自己点検責任者”と”自己点検担当者”はあるけど、”点検”のことは、入っていなくて大丈夫かな？
 そのときの話し合いに出席できていなかったので、既に議論されていたことであったらすみません。。
 特に深い意味はなければ、”点検”でまとめてしまってもよいのかなぁと、思ってみたりしました。

*** taka 
 了解です。
 組織図(案)、手順書(案)は、PMDAでの成果物なので、あまり手をいれる気はないのですが、
 なんとなく、修正しました。

** スライド以外
*** moro
 当日の資料配布については、事情があれば配らない、一部のスライドのみ配布等、出向者で決めてよいと
 事務局の方がいってました。

*** koku
 最後に以前メールでお知らせしたのが送信できていなかったようなのでご連絡です。

 12/16の報告会ですが、私が報告会の日程を誤認しており、当日は以前から決まっていた他の予定が入っておりました。
 当日は遠方におり、参加できるか調整していたのですが少々厳しそうなので、松木さんに相談して今回は欠席ということにしました。

 まだ名古屋の事務局には欠席の連絡を入れておりませんので、近日中に慶應の事務局から連絡があるかもしれません。

 報告会やその前後の会も欠席となり大変ご迷惑おかけしますが宜しくお願いいたします。

* [2019-12-06 Fri] from 諸橋
お二人からいただいた情報をもとに、添付スライド２ページ目を若干修正しました。
訂正前のものに上書きしてしまい…確認しづらい状況です。ごめんなさい。。

訂正としては、HISとレプリカを枠で込んだところです。
その枠内をHISとしてぼやかしてみたところです。部門システムもHISとするのが、より正しいだろうか…悩む。
アドバイスほしいのです。

ページ３との整合性がとれなくなるので、ページ３も”HIS”を”電子カルテ”に書き換えて、
電子カルテ+レプリカ=HIS にした方がいいかな？？

* [2019-12-06 Fri] from 伊藤
報告会資料の担当分について対応しました。
1ファイルに部門会と傷病名のスライドをまとめました。

細かいことですが、悩ましいところがあります。
傷病名スライドに「標準マスタ概念外」と書きました。
MID-NETでの傷病名標準化対象外の中に、以下があります。
①１つのローカルコードに複数傷病名が設定されている（例：１２３４５　 頭痛、胃癌）
②MID-NETマスタの標準病名の概念と異なる（例：のう胞）

今回のスライドでは①も概念外としてひっくるめてしまったのですが、概念外の使い方は合っていますか？
概念といわれるとイマイチピンと来ませんが、標準マスタに当たらないものとしてしまうと、機械的に一致しないものとも捉えられそうで。

机上で考えれば①はそもそも論外なので②だけでもよいのですが、実際、②は微々たる件数だと思います。①の方が意外とありました（違っていたら私の知識が浅いです、すみません）。
なのでどちらかといえば①を主張したいのですが、調査票に挙がった①のパターンがいつのデータのものか分からないので、今はそんな入れ方してないよーといわれると、今に合った内容ではなくなってしまうし、、悩んでいます。
他によい表現があれば、ご意見願います。
  
* [2019-12-04 Wed] from 伊藤
- 1枚目：MID-NETにおる品質管理⇒おける
  - typo 修正しました
- 6、７枚目：協力機関⇒協力医療機関
  - typo 修正しました
- 11枚目：自己点検と点検作業の考え方が反対のように思います。自己点検がきちんと行われているかを別の視点で確認するのが点検だったように思います。理解が誤っておりましたらすみません。
  - 諸橋さんからの指摘もあり、そういうつもりで記載したのですが、記載の甘さが残っていると実感しました
  - リライトします
- 22枚目：傷病名の標準マスタ入手方法について、診療報酬情報提供サービスが入っているのはなぜでしょうか。
  - レセ電データをいれたため。必要かな？
- 34枚目：公にする前に（）の中を出向者MTGで話し合いたいです。
  - 了解です。ここについては議論しておいてよいかと。
- 28～35枚目：出向者が貢献できることをまとめているスライドと思いますが、具体的には、提案してどのようなことに貢献できると説明しているスライドになるのでしょうか。理解が悪くすみません。
  - PMDAの経験を活かすには土壌が必要で、その上でしか経験は生きないことを、一貫して記載しているつもりです。
  - ただ、ちょっと標語的なものを思いついたので、追記しました。

* [2019-12-04 Wed] from 諸橋
- ①P3　医療情報データベースの先駆けであるMID-NET～　MID-NETは医療情報データを解析するためのシステムなのかなと。データベースとだけくくってしまってよいのだろうか？と思いました。
  - これは、出典を明記していないのですが、どうやらAMED資料からの抜粋、とのことです
  - 文章かえてもいいけど、そもそも出向の目的は僕等で決めたわけでもないし...
- ②P4　標準化A～D　品質管理A　今更なのですが、このABCDってなんだっけ？とわからなくなりました。すみません。。
  - ヒトみたい。Aさん、Bさんといったかんじ
  - この辺も元資料そのままです
- ③P５　なんかカッコイイ（笑）
  - ほめてもらた。ありがとうございます。
- ④P8とか　PMDAの資料だからなんか書かないとよくないですかね？？心配性で。。
  - PMDA資料については、Webからのパクリなので、クレジット&URL をいれるつもり
  - そんなこんなで、早めに原稿をあげる必要あるかな、と。
- ⑤P11　伊藤さんとかぶるかな？品質管理チームでおこなっていた“自己点検”は、同じチーム内の別の作業者が、報告書の内容等確認人してくれていました。私の他の方の作業の確認を“自己点検”としてやっていました。点検チームでは、他のチームの方が行っているなにかしらの確認？作業（自己点検？）が行われているか否かを、“点検作業”として行っていました。他のチームの方法はあまり把握していないのです…。そして、いろいろ記憶があいまいになってきてます…
  - 伊藤さんの分にも記載したように、記載をリライトします
- ⑥P12　気持ち　図中の①しかしてないことを明確に伝えたい！！
  - 出向でやったこと、という意味ですよね
  - 3,4,5はシステムバリデーションですし
  - 一枚追加して、ハイライトします？
- ⑦P32-33　表したいことを今度教えてほしい。理解が悪くてすみません…
  - 部門会の必要性をリードしているつもりです
  - 横のつながりの重要性、つたわらないか
- ⑧P34　もしだった…　“核施設より”または。赤枠の部分にひと手間、的なことをすると、専門職といわれる人が今のメンバー（会議に参加するような）に限らず、　現場でマスタ管理してる人が必要だよ！！ってのが、より伝えられそうと思ってみた。
  - ごめん、よくわからん...
- ⑨P35　システムの管理的なところもいれたいのです。P12でいう①以外のところ、の意味です！あと、具体的なとこってのも、もう少し入れたいな。　　　　手順書ってので網羅されているといえば、そうともとれるのだが。なんとなく！
  - なんとなくわかった
  - ちょっと考えます
