* [2019-12-04 Wed] from 諸橋
- ①P3　医療情報データベースの先駆けであるMID-NET～　MID-NETは医療情報データを解析するためのシステムなのかなと。データベースとだけくくってしまってよいのだろうか？と思いました。 
- ②P4　標準化A～D　品質管理A　今更なのですが、このABCDってなんだっけ？とわからなくなりました。すみません。。 
- ③P５　なんかカッコイイ（笑） 
- ④P8とか　PMDAの資料だからなんか書かないとよくないですかね？？心配性で。。 
- ⑤P11　伊藤さんとかぶるかな？品質管理チームでおこなっていた“自己点検”は、同じチーム内の別の作業者が、報告書の内容等確認人してくれていました。私の他の方の作業の確認を“自己点検”としてやっていました。点検チームでは、他のチームの方が行っているなにかしらの確認？作業（自己点検？）が行われているか否かを、“点検作業”として行っていました。他のチームの方法はあまり把握していないのです…。そして、いろいろ記憶があいまいになってきてます… 
- ⑥P12　気持ち　図中の①しかしてないことを明確に伝えたい！！ 
- ⑦P32-33　表したいことを今度教えてほしい。理解が悪くてすみません…
- ⑧P34　もしだった…　“核施設より”または。赤枠の部分にひと手間、的なことをすると、専門職といわれる人が今のメンバー（会議に参加するような）に限らず、　現場でマスタ管理してる人が必要だよ！！ってのが、より伝えられそうと思ってみた。 
- ⑨P35　システムの管理的なところもいれたいのです。P12でいう①以外のところ、の意味です！あと、具体的なとこってのも、もう少し入れたいな。　　　　手順書ってので網羅されているといえば、そうともとれるのだが。なんとなく！
* [2019-12-04 Wed] from 伊藤
- 1枚目：MID-NETにおる品質管理⇒おける
- 6、７枚目：協力機関⇒協力医療機関
- 11枚目：自己点検と点検作業の考え方が反対のように思います。自己点検がきちんと行われているかを別の視点で確認するのが点検だったように思います。理解が誤っておりましたらすみません。
- 22枚目：傷病名の標準マスタ入手方法について、診療報酬情報提供サービスが入っているのはなぜでしょうか。
- 34枚目：公にする前に（）の中を出向者MTGで話し合いたいです。
- 28～35枚目：出向者が貢献できることをまとめているスライドと思いますが、具体的には、提案してどのようなことに貢献できると説明しているスライドになるのでしょうか。理解が悪くすみません。
